---

version: '3.3'

services:

  nginx:
    build:
      context: services/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - "./services/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - app

  app:
    build:
      context: services/app
      dockerfile: Dockerfile.development
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      PYTHONUSERBASE: ./vendor
    volumes:
      - "~/.bash_history:/.bash_history"
      - "./services/app:/usr/src/app:cached"
      - "/tmp:/tmp:delegated"