---

version: '3.3'

services:

  db:
    image: postgres

#  nginx:
#    build:
#      context: services/nginx
#      dockerfile: Dockerfile
#    ports:
#      - "9000:80"
#    depends_on:
#      - app

  app:
    build:
      context: services/app
      dockerfile: Dockerfile.development
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8080:8000"
    volumes:
      - "~/.bash_history:/.bash_history"
      - "./services/app:/usr/src/app:cached"
      - "/tmp:/tmp:delegated"
    depends_on:
      - db