FROM python:3.7.2

ENV PYTHONUNBUFFERED 1
ENV PROJECT_ROOT /usr/src/app

RUN mkdir -p /usr/src/app

WORKDIR $PROJECT_ROOT

COPY requirements.txt $PROJECT_ROOT
RUN apt-get update
RUN pip install --upgrade pip